dist: trusty
sudo: required
language: rust
rust:
- stable
git:
  depth: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - cmake
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
    - gcc
    - binutils-dev

cache:
  cargo: true
  timeout: 240
  directories:
  - "$HOME/.cargo"
  - "$TRAVIS_BUILD_DIR/target"

env:
  global:
  - RUST_BACKTRACE="1"
  - RUSTFLAGS="-C debug-assertions"

matrix:
  include:
  - os: linux
    env: CI_JOB="test"        CI_JOB_ARGS="xyz"
  - os: linux
    env: CI_JOB="release"     CI_JOB_ARGS=

script:
- bash .ci/general-jobs

before_cache:
- rm -rf $TRAVIS_BUILD_DIR/target/tmp

before_deploy:
- bash .ci/release-jobs

deploy:
  provider: releases
  api_key:
    secure: zTOoHS2hItSA/YUVTaO6S7JdYB5oHK5ldcD8A47xB2KyWnc34Va5Z3ig88cx9g4E8rqotbnCm02mv5VNJhTCG0bIkIxb9g6h0uW8Na9x1Ck1+bbMubEt5v7QkhqtOlK9bJcy9Q5o0fsvjm0us82Bxnec0srocQr7AWjunhlT0hHYoqQTxxNlI7hBsoHRFMUz39novoNW2hCpSddGMBUQicKYquOcLtM+SwRAkByvsF6sl6S28Cul6UBT35ukb9OsCdkIOSfZcbw3pkw99IbEoTVEll2vO7gtn1epB5BT7spw5HeFBWIfFPZiwcsHvtJ9SAtuWniYbXohFyyI0RHiB2gCoezgtVpWIj0DA1LP6JARYqcuCj3yXv2kkd8xdYUYjWG/uYKJaMfnfu/4pwEq6/kAccQmesDC7X8UrfIsPMmzOJ3s83+QJq4bdzyObBSqlVE2oHRunOm+3wrj8uLMMpqzZK/F/q35B/fSx1L0D5dWFG+NLDfYqGnoRY2KMNZwaD384bsmxmtae377Q9KY5KSWR0V9JWE/bbDgzuW2xZj7MF4YCmvKsCS2+47OFBd7eFO41vOJbB73X+bL9+uT9qblzfNL/oLNhVUqKEmmXtONF3+KV4UIJ23z5Xqibj1OGS3ACAEvw2sGbUJURO96bO4sDVBHQjwKPm0yKHUE7cM=
  file_glob: true
  file: target/release/grinrelay-*.*
  skip_cleanup: true
  on:
    repo: gigglewallet/grinrelay
    tags: true
