dist: trusty
sudo: required
language: rust
rust:
- stable
git:
  depth: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - cmake
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
    - gcc
    - binutils-dev

cache:
  cargo: true
  timeout: 240
  directories:
  - "$HOME/.cargo"
  - "$TRAVIS_BUILD_DIR/target"

env:
  global:
  - RUST_BACKTRACE="1"
  - RUSTFLAGS="-C debug-assertions"

matrix:
  include:
  - os: linux
    env: CI_JOB="test"        CI_JOB_ARGS="xyz"
  - os: linux
    env: CI_JOB="release"     CI_JOB_ARGS=

script:
- bash .ci/general-jobs

before_cache:
- rm -rf $TRAVIS_BUILD_DIR/target/tmp

before_deploy:
- bash .ci/release-jobs

deploy:
  provider: releases
  api_key:
    secure: N3tqOigoX5esp8+L+sIGRYzcZuQ/9m/pui77RzHm93w39ISaNLkFALAsqK2p8cBX5DdVoDom63Flmon2fb6kXpNbsWPLhoO//vfvzhKo+6otXOYQpOjx58sXUsNBivNL01LJ9XpgdWLhDw2E/h54LrNqkHaPsGdhFbtsnqpXkQNXfGRfSKUVQ5AToGoS9Aj4fDxWWm9vMhayScyWZrQykk66F6EzJam28w0v2n7m+f8U7wID77HGOnmTP94FGSN5VnRC3rP+fGFuw28AphMv2O89HuFOL9uawjy4o/sf3jNBsYjX2O/9ljFN24gelSkWtxaI6KcJ5z3jbbxHz/mKBDzRejy7Pfd40BmgcDMgGjssNEy7Op2zLxiVkVlnhhC5AWIlS9eOsF4wkTh/m5miKIXN0KIdZM1wsacr9AqKjW1OuDDYLGphTddxF9FwD4rYpTh5KBPinHjlqCXOjq+WygOutTlXvL5YUv+eQYw95lr1Lkv06xU5nohg5J2LzcSpJAAhLjdEtpoBGvlVbGNJ3ZWwkW2fGkjAeR6nwA2ojT31LZodAiwpooYBRaqckGQ8sczN8aqUvpiQ+lmBRqpA15+yePYsEY8Aqr8CabE/R6h4AkI5w4300jlKbIxJ36A013lyDRO7W2iBXRTQGgT0IJImyimmQv1XnZYp1Pn6Zlo=
  file_glob: true
  file: target/release/grinrelay-*.*
  skip_cleanup: true
  on:
    repo: gigglewallet/grinrelay
    tags: true
